import { auth } from "@clerk/nextjs/server";
import Link from "next/link";
import { redirect } from "next/navigation";

import { getMembershipRole, getPartners, getTeamOverview, getWorkspace } from "@/lib/db";

import { inviteTeamMember } from "./actions";

export default async function TeamPage() {
  const { userId, orgId } = await auth();
  if (!userId || !orgId) redirect("/sign-in");
  const workspace = await getWorkspace(orgId);
  if (!workspace || await getMembershipRole(workspace.id, userId) !== "coordinator") redirect("/portal");
  const [team, partners] = await Promise.all([getTeamOverview(workspace.id), getPartners(workspace.id)]);

  return <main className="min-h-screen bg-[#f7f6f2] px-6 py-10 text-[#18231e]"><div className="mx-auto max-w-5xl"><Link href="/coordinator" className="font-semibold text-[#285d3c]">← Coordinator board</Link><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.1fr]"><section className="rounded-[2rem] bg-[#183d2a] p-7 text-white"><p className="text-xs font-bold tracking-[0.2em] text-[#b6d59a]">TEAM ACCESS</p><h1 className="mt-3 text-3xl font-semibold">Give every person the right workspace.</h1><p className="mt-3 text-sm leading-6 text-[#c9d8cd]">Invites enter through Clerk. Last Mile records the operating role here, so nobody can select a privileged role for themselves.</p><form action={inviteTeamMember} className="mt-7 space-y-4"><label className="block text-sm font-semibold">Email<input name="email" type="email" required className="mt-1.5 w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-white outline-none placeholder:text-white/50" placeholder="teammate@example.org" /></label><label className="block text-sm font-semibold">Role<select name="role" className="mt-1.5 w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-white"><option className="text-black" value="volunteer">Volunteer</option><option className="text-black" value="partner_manager">Partner manager</option></select></label><label className="block text-sm font-semibold">Partner <span className="font-normal text-[#c9d8cd]">(required for partner managers)</span><select name="partnerId" className="mt-1.5 w-full rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-white"><option className="text-black" value="">No partner assignment</option>{partners.map((partner) => <option className="text-black" key={partner.id} value={partner.id}>{partner.name}</option>)}</select></label><button className="w-full rounded-xl bg-[#e9f3d5] px-4 py-3 text-sm font-bold text-[#183d2a]">Send role-aware invite</button></form></section><section className="rounded-[2rem] border border-[#e2e2d9] bg-white p-7 shadow-sm"><h2 className="text-xl font-semibold">Current operating roles</h2><div className="mt-5 space-y-3">{team.members.map((member) => <div key={member.userId} className="rounded-xl bg-[#f5f7f2] p-4"><p className="font-mono text-xs text-[#68776d]">{member.userId}</p><p className="mt-1 text-sm font-semibold capitalize">{member.role.replace("_", " ")}{member.partnerName ? ` · ${member.partnerName}` : ""}</p></div>)}</div><h2 className="mt-8 text-xl font-semibold">Pending invites</h2><div className="mt-4 space-y-3">{team.invites.length ? team.invites.map((invite) => <div key={invite.email} className="rounded-xl border border-dashed border-[#cfd8d0] p-4"><p className="font-semibold">{invite.email}</p><p className="mt-1 text-sm text-[#68776d] capitalize">{invite.role.replace("_", " ")}{invite.partnerName ? ` · ${invite.partnerName}` : ""}</p></div>) : <p className="text-sm text-[#68776d]">No invitations are waiting.</p>}</div></section></div></div></main>;
}
